from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parent.parent
WRAPPING_DIR = ROOT / 'Wrapping'
RIBBON_DIR = ROOT / 'Ribbon'
TAGS_DIR = ROOT / 'Tags'
OUTPUT_FILE = ROOT / 'asset-data.js'


def normalize_category_name(name: str) -> str:
    name = name.replace('_', ' ').replace('-', ' ').strip()
    if name.islower():
        return ' '.join(word.capitalize() for word in name.split())
    return name


def list_image_files(folder: Path):
    return sorted(
        [p.name for p in folder.iterdir() if p.is_file() and not p.name.startswith('.')]
    )


def build_paper_categories():
    categories = []
    if not WRAPPING_DIR.exists():
        return categories
    for subdir in sorted([p for p in WRAPPING_DIR.iterdir() if p.is_dir()], key=lambda p: p.name.lower()):
        images = list_image_files(subdir)
        if images:
            categories.append({
                'category': normalize_category_name(subdir.name),
                'images': images
            })
    return categories


def build_ribbon_categories():
    images = list_image_files(RIBBON_DIR) if RIBBON_DIR.exists() else []
    return [{'category': 'Ribbon', 'images': images}] if images else []


def build_tag_categories():
    categories = []
    if not TAGS_DIR.exists():
        return categories
    for subdir in sorted([p for p in TAGS_DIR.iterdir() if p.is_dir()], key=lambda p: p.name.lower()):
        images = list_image_files(subdir)
        if images:
            categories.append({
                'category': normalize_category_name(subdir.name),
                'folder': subdir.name,
                'images': images
            })
    return categories


def render_js_constant(name, value):
    return f"const {name} = {json.dumps(value, indent=4, ensure_ascii=False)};\n\n"


def main():
    paper_categories = build_paper_categories()
    ribbon_categories = build_ribbon_categories()
    tag_categories = build_tag_categories()

    content = (
        '/* Generated by tools/generate_asset_data.py.\n'
        '   Run this script whenever you add or remove files in Wrapping/, Ribbon/, or Tags/. */\n\n'
        + render_js_constant('paperCategories', paper_categories)
        + render_js_constant('ribbonCategories', ribbon_categories)
        + render_js_constant('tagCategories', tag_categories)
    )

    OUTPUT_FILE.write_text(content, encoding='utf-8')
    ribbon_count = len(ribbon_categories[0]['images']) if ribbon_categories else 0
    print(f"Written {OUTPUT_FILE.relative_to(ROOT)} with {len(paper_categories)} wrapping categories, {ribbon_count} ribbon images, {len(tag_categories)} tag categories.")


if __name__ == '__main__':
    main()
